    
version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/getmilly/grok
  docker:
    - image: circleci/golang:1.11
commands:
  autotag:
    steps:
      - run: |
          make install-autotag

jobs:
  run-tests:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Rebase
          command: make run-rebase
      - run:
          name: Install dep
          command: make install-dep
      - run:
          name: Build Package
          command: make build-package
      - run:
          name: Run Tests
          command: make run-tests
      - persist_to_workspace:
          root: .
          paths:
              - .
  release-vesion:
    <<: *defaults
    steps:
      - checkout
      - autotag
      - run:
          name: Tag Git Version
          command: make tag-version

workflows:
  version: 2
  build-deploy:
    jobs:
      - run-tests

      - release-vesion:
          requires:
            - run-tests
          filters:
            branches:
              only:
                - master